services:
  - type: web
    name: api-harley-davidson
    runtime: node
    plan: free
    region: oregon
    rootDir: .
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_VERSION
        value: 20.18.1
      - key: NODE_ENV
        value: production
