services:
  # Backend API
  - type: web
    name: api-harley-davidson
    runtime: node
    plan: free
    region: oregon
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.18.1
      - key: NODE_ENV
        value: production

  # Frontend
  - type: static
    name: harley-davidson-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    rootDir: frontend
    envVars:
      - key: VITE_API_URL
        value: https://api-harley-davidson.onrender.com
